name: Check the source code in the repository
on:
  pull_request:
    branches: [master]
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run ESLint
        run: npm run lint
